### PR TITLE
add buildkite pipeline

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I think you need this:

```
steps:
  - label: "WeakConvergence"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'WeakConvergence'
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

steps:
  - label: "WeakAdaptive"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'WeakAdaptive'
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
```

**Comment by DilumAluthge** [comment]
This should be sufficient for the fastcpu tag:

```yaml
steps:
  - label: "WeakConvergence"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
      fastcpu: "true"
    env:
      GROUP: 'WeakConvergence'
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "WeakAdaptive"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
      fastcpu: "true"
    env:
      GROUP: 'WeakAdaptive'
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
```

**Comment by DilumAluthge** [comment]
@ChrisRackauckas Since currently no agents have the required tags, Buildkite is going to be stuck waiting for an agent.

You'll need to make a PR to https://github.com/JuliaGPU/buildkite

The agents are listed here: https://github.com/JuliaGPU/buildkite/tree/main/agents

For each agent that you want to add the `fastcpu=true` tag to, make a PR to add the tag.

I made this PR as an example to demonstrate: https://github.com/JuliaGPU/buildkite/pull/10

**Comment by ChrisRackauckas** [comment]
Looks like if I cut it down to one group it doesn't work again? I'm confused by that.

**Comment by DilumAluthge** [comment]
The reason it's not working now is because of this. We haven't actually added the fastcpu tag to any agents.

> @ChrisRackauckas Since currently no agents have the required tags, Buildkite is going to be stuck waiting for an agent.
> 
> You'll need to make a PR to https://github.com/JuliaGPU/buildkite
> 
> The agents are listed here: https://github.com/JuliaGPU/buildkite/tree/main/agents
> 
> For each agent that you want to add the `fastcpu=true` tag to, make a PR to add the tag.
> 
> I made this PR as an example to demonstrate:
> 
> [JuliaGPU/buildkite#10](https://github.com/JuliaGPU/buildkite/pull/10)
> 
> https://github.com/JuliaGPU/buildkite/pull/10/files

**Comment by ChrisRackauckas** [comment]
oh haha oops.

**Comment by DilumAluthge** [comment]
I was going to make the PR to JuliaGPU/buildkite myself, but I realized I don't actually know which machines have fast CPUs and which machines have slow CPUs.

**Comment by ChrisRackauckas** [comment]
well I'll merge this. 

https://github.com/JuliaGPU/buildkite/pull/12
https://github.com/JuliaGPU/buildkite/pull/11

should get us some agents.

**Pull request merged**
