### PR TITLE
CI for LTS

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@frankschae this is the last one I've been working on.

**Comment by ChrisRackauckas** [comment]
We might need to move some tests to the buildkite, but let's see if this is ready to merge first 😅

**Comment by ChrisRackauckas** [comment]
Some of those test failures on v1.7 look way off?

**Comment by frankschae** [comment]
Yes... but I think the errors have already alternated at least once (i.e. once it failed at 1.6, then at 1.7) when increasing the number of trajectories. 
The number of trajectories is still on the lower end. Roessler uses 1e8 to 1e9 (https://link.springer.com/article/10.1007/s10543-007-0130-3)

**Comment by ChrisRackauckas** [comment]
I'd say, swap all of those big weakconvergence tests to buildkite right now. This might take awhile longer than I had originally thought 😅

**Comment by frankschae** [comment]
The tests, where I've just increased the number of trajectories, were still relatively small up to now (except the 1e7 ... that one is indeed a little odd ..). Basically,  we haven't seen those before because weak_convergence2 was failing and the other tests were canceled and didn't run through.

**Comment by frankschae** [comment]
> I'd say, swap all of those big weakconvergence tests to buildkite right now. This might take awhile longer than I had originally thought 😅

yup, good idea. I'll do it.

**Comment by ChrisRackauckas** [comment]
oops, looks like this is done but a regression on master needs to be fixed. Good time to have the tests working. Thanks @frankschae  😅

**Pull request merged**
