### PR TITLE
overload _alg_autodiff

### PR DESCRIPTION
**Pull request by vpuri3**
fix downstream errors in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917

@gaurav-arya can you review?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
To make the transition simpler, it may be good to yank all other v2 releases.

**Comment by xtalax** [comment]
@ChrisRackauckas  v2 of what, and which packages?

**Comment by ChrisRackauckas** [comment]
yank releases of StochasticDiffEq which allow SparseDiffTools v2.

**Comment by ChrisRackauckas** [comment]
Looking around, we never did do a SparseDiffTools v2 compatible release so the versions bounds naturally work well here.

**Comment by vpuri3** [comment]
it's grabbing ODE.jl 6.51.2. 

https://github.com/SciML/StochasticDiffEq.jl/actions/runs/5095012736/jobs/9159498470?pr=531#step:6:60

**Comment by vpuri3** [comment]
@ChrisRackauckas looks like this needs an OrdinaryDiffEq release.

https://github.com/SciML/StochasticDiffEq.jl/actions/runs/5098413712/jobs/9165536977?pr=531#step:5:20

**Pull request merged**
