### PR TITLE
controllers

### PR DESCRIPTION
**Pull request by ranocha**
Companion PR to SciML/OrdinaryDiffEq.jl#1384. Locally, all tests pass for me.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Does StochasticDelayDiffEq need updates?

**Comment by ranocha** [comment]
> StochasticDelayDiffEq

Maybe, I didn't know about that :sweat_smile:

**Comment by ranocha** [comment]
Yeah, it will need some updates, at least for the options

**Comment by ChrisRackauckas** [comment]
The remaining convergence tests don't use the controllers.

**Comment by ChrisRackauckas** [comment]
@frankschae some of those DiffEqNoiseProcess tolerances are a little low:

https://github.com/SciML/StochasticDiffEq.jl/runs/2621672149#step:7:321

1e-16 won't necessarily be resolvable as a relative tolerance with Float64.

**Comment by frankschae** [comment]
I see.. I made a note to bump the tolerances for them.

**Pull request merged**
