### PR TITLE
Fix type inference of interpolation

### PR DESCRIPTION
**Pull request by devmotion**
Fixes https://github.com/SciML/StochasticDiffEq.jl/issues/351.

That's the good thing. The bad thing is that the implementation is just copied from OrdinaryDiffEq.

### CODE REVIEW

**Comment by rvignolo** [comment]
Hi, thanks for this! 

I was wondering, what are the differences between the `OrdinaryDiffEq._searchsortedlast` and `Base.searchsortedlast`?

**Comment by ChrisRackauckas** [comment]
`OrdinaryDiffEq._searchsortedlast` was a lot faster IIRC

**Comment by rvignolo** [comment]
thank you both.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqBase.jl/blob/master/src/interpolation.jl is the last spot where this kind of code also exists. We should try to get it all merged to the same system, but it's never been the highest priority.

**Pull request merged**
