### PR TITLE
iip for RI1 with tests

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Cherrypicked https://github.com/SciML/StochasticDiffEq.jl/pull/289 @frankschae

### CODE REVIEW

**Comment by frankschae** [comment]
I haven't set `ensemblealg=EnsembleThreads()` to `EnsembleGPUArray()` yet. Is there a nice way to check if GPU is available and then switch between the options?

**Comment by ChrisRackauckas** [comment]
I think there is in the CUDA API, but for esimplicity let's just set the tests up to always GPU since then we can keep it in a separate group.

**Comment by ChrisRackauckas** [comment]
Or if it's fast enough for CPU now, ignore it.

**Comment by frankschae** [comment]
These test should now be (relatively) fast
```
1
2
3
4
 13.949087 seconds (272.95 M allocations: 16.118 GiB, 15.62% gc time)
DRI1:1.7030590699025905
1
2
3
4
 19.453826 seconds (690.07 M allocations: 29.881 GiB, 26.78% gc time)
RI1:1.7250057126512144
1
2
3
4
 17.500431 seconds (174.84 M allocations: 15.603 GiB, 14.64% gc time)
DRI1:1.7030590699025865
1
2
3
4
 23.561641 seconds (425.61 M allocations: 27.405 GiB, 21.05% gc time)
RI1:1.725005712651214
1
2
3
4
 13.933221 seconds (100.05 M allocations: 11.594 GiB, 16.05% gc time)
DRI1:1.8519941401466886
1
2
3
4
 17.238613 seconds (185.77 M allocations: 15.815 GiB, 19.32% gc time)
RI1:2.841177370115077
1
2
3
4
 10.450973 seconds (56.18 M allocations: 9.049 GiB, 16.05% gc time)
DRI1:2.91342508142561
1
2
3
4
 10.738035 seconds (61.56 M allocations: 9.077 GiB, 16.50% gc time)
RI1:3.0496799700302906

```

**Comment by ChrisRackauckas** [comment]
alright cool, so no GPU needed for now.

**Pull request merged**
